### ISSUE TITLE
Vermont

### ISSUE THREAD

**Issue by cwulfman** [TrustTheVote-Project/Rocky-OVR#501]

**Comment by cwulfman** [comment]
There is no abr_state_methods/vt.rb.  Why not?

PDFTK breaks when trying to generate test.pdf; don't know if that matters.

**Comment by amekelburg** [comment]
Probably because VT was online-only previously.
Not sure if PDFTK break matters - probably. I've seen issues when the fonts aren't standard fonts.

**Comment by amekelburg** [comment]
*fonts for the fillable fields. THey should all be helvettica I think
